<?php
/**
 * ObjectSerializer
 *
 * PHP version 5
 *
 * @category Class
 * @package  SprintPay\Client
 * @author   SprintPay team/ daniel ngantchou
 * @link     https://github.com/sprintpay/sprintpay-api-php-client
 */

/**
 * Sprint-pay payment for developper
 *
 * configuration class for sprint-pay payment api.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: sprint-pay@sprint-pay.com
 * source: https://github.com/sprintpay/sprintpay-api-php-client
 * SprintPay rainbow-cl
 */

/**
 * NOTE: This class is auto generated by the sprintPay code generator program.
 * https://github.com/sprintpay/sprintpay-api-php-client
 * Do not edit the class manually.
 */
namespace SprintPay\Client;

/**
 * PaymentCardReponseTest Class Doc Comment
 *
 * @category    Class */
// * @description PaymentCardReponse
/**
 * @package     SprintPay\Client
 * @author      SprintPay Codegen team
 * @link        https://github.com/sprintpay/sprintPay-api-php-client
 */
class PaymentCardReponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PaymentCardReponse"
     */
    public function testPaymentCardReponse()
    {
    }

    /**
     * Test attribute "order_status"
     */
    public function testPropertyOrderStatus()
    {
    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {
    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {
    }

    /**
     * Test attribute "invoice_number"
     */
    public function testPropertyInvoiceNumber()
    {
    }

    /**
     * Test attribute "sp_transaction_id"
     */
    public function testPropertySpTransactionId()
    {
    }

    /**
     * Test attribute "id_sp_marchand"
     */
    public function testPropertyIdSpMarchand()
    {
    }
}
