<?php
/**
 * ObjectSerializer
 *
 * PHP version 5
 *
 * @category Class
 * @package  SprintPay\Client
 * @author   SprintPay team/ daniel ngantchou
 * @link     https://github.com/sprintpay/sprintpay-api-php-client
 */

/**
 * Sprint-pay payment for developper
 *
 * configuration class for sprint-pay payment api.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: sprint-pay@sprint-pay.com
 * source: https://github.com/sprintpay/sprintpay-api-php-client
 * SprintPay rainbow-cl
 */

/**
 * NOTE: This class is auto generated by the sprintPay code generator program.
 * https://github.com/sprintpay/sprintpay-api-php-client
 * Do not edit the class manually.
 */

namespace Swagger\Client;

/**
 * PaymentMobileReponseTest Class Doc Comment
 *
 * @category    Class */
// * @description PaymentMobileReponse
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/sprintp/sprintpay-api-php-client
 */
class PaymentMobileReponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PaymentMobileReponse"
     */
    public function testPaymentMobileReponse()
    {
    }

    /**
     * Test attribute "transaction_id"
     */
    public function testPropertyTransactionId()
    {
    }

    /**
     * Test attribute "status_desc"
     */
    public function testPropertyStatusDesc()
    {
    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {
    }

    /**
     * Test attribute "reciever_number"
     */
    public function testPropertyRecieverNumber()
    {
    }

    /**
     * Test attribute "sender_number"
     */
    public function testPropertySenderNumber()
    {
    }

    /**
     * Test attribute "operation_type"
     */
    public function testPropertyOperationType()
    {
    }

    /**
     * Test attribute "status_code"
     */
    public function testPropertyStatusCode()
    {
    }

    /**
     * Test attribute "op_comment"
     */
    public function testPropertyOpComment()
    {
    }

    /**
     * Test attribute "processing_number"
     */
    public function testPropertyProcessingNumber()
    {
    }

    /**
     * Test attribute "operation_date"
     */
    public function testPropertyOperationDate()
    {
    }

    /**
     * Test attribute "sp_merchand"
     */
    public function testPropertySpMerchand()
    {
    }

    /**
     * Test attribute "id_sp_marchand"
     */
    public function testPropertyIdSpMarchand()
    {
    }
}
