<?php
/**
 * ObjectSerializer
 *
 * PHP version 5
 *
 * @category Class
 * @package  SprintPay\Client
 * @author   SprintPay team/ daniel ngantchou
 * @link     https://github.com/sprintpay/sprintpay-api-php-client
 */

/**
 * Sprint-pay payment for developper
 *
 * configuration class for sprint-pay payment api.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: sprint-pay@sprint-pay.com
 * source: https://github.com/sprintpay/sprintpay-api-php-client
 * SprintPay rainbow-cl
 */

/**
 * NOTE: This class is auto generated by the sprintPay code generator program.
 * https://github.com/sprintpay/sprintpay-api-php-client
 * Do not edit the class manually.
 */

namespace SprintPay\Client;

use \SprintPay\Client\Configuration;
use \SprintPay\Client\ApiException;
use \SprintPay\Client\ObjectSerializer;

/**
 * MobilePaymentApiTest Class Doc Comment
 *
 * @category Class
 * @package  SprintPay\Client
 * @author   SprintPay Codegen team
 * @link     https://github.com/sprintpay/sprintpay-api-php-client
 */
class MobilePaymentApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for mobilemoney
     *
     * Make a new mobilemoney payment.
     *
     */
    public function testMobilemoney()
    {
    }

    /**
     * Test case for mobilestatus
     *
     * check the status of mobile payment request using processingNumber.
     *
     */
    public function testMobilestatus()
    {
    }

    /**
     * Test case for orangemoney
     *
     * Make an payment using orangemoney.
     *
     */
    public function testOrangemoney()
    {
    }
}
